# SPDX-FileCopyrightText: 2025 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.1.4.2025.21195.1");
  script_cve_id("CVE-2025-0840", "CVE-2025-11083", "CVE-2025-11412", "CVE-2025-11413", "CVE-2025-11414", "CVE-2025-1147", "CVE-2025-1148", "CVE-2025-1149", "CVE-2025-11494", "CVE-2025-11495", "CVE-2025-1150", "CVE-2025-1151", "CVE-2025-1152", "CVE-2025-1153", "CVE-2025-1176", "CVE-2025-1178", "CVE-2025-1179", "CVE-2025-1180", "CVE-2025-1181", "CVE-2025-1182", "CVE-2025-3198", "CVE-2025-5244", "CVE-2025-5245", "CVE-2025-7545", "CVE-2025-7546", "CVE-2025-8224", "CVE-2025-8225");
  script_tag(name:"creation_date", value:"2025-12-16 16:47:44 +0000 (Tue, 16 Dec 2025)");
  script_version("2025-12-17T05:46:28+0000");
  script_tag(name:"last_modification", value:"2025-12-17 05:46:28 +0000 (Wed, 17 Dec 2025)");
  script_tag(name:"cvss_base", value:"5.1");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:H/Au:N/C:P/I:P/A:P");
  script_tag(name:"severity_vector", value:"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H");
  script_tag(name:"severity_origin", value:"NVD");
  script_tag(name:"severity_date", value:"2025-07-30 15:59:59 +0000 (Wed, 30 Jul 2025)");

  script_name("SUSE: Security Advisory (SUSE-SU-2025:21195-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2025 Greenbone AG");
  script_family("SuSE Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/suse_sles", "ssh/login/rpms", re:"ssh/login/release=(SLES16\.0\.0)");

  script_xref(name:"Advisory-ID", value:"SUSE-SU-2025:21195-1");
  script_xref(name:"URL", value:"https://www.suse.com/support/update/announcement/2025/suse-su-202521195-1.html");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1236632");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1236976");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1236977");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1236978");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1236999");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237000");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237001");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237003");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237005");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237018");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237019");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237020");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237021");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1237042");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1240870");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1243756");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1243760");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1246481");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1246486");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1247105");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1247114");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1247117");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1250632");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1251275");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1251276");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1251277");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1251794");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1251795");
  script_xref(name:"URL", value:"https://lists.suse.com/pipermail/sle-security-updates/2025-December/023546.html");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'binutils' package(s) announced via the SUSE-SU-2025:21195-1 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"This update for binutils fixes the following issues:

Changes in binutils:

- Update to current 2.45 branch at 94cb1c075 to include fix
 for PR33584 (a problem related to LTO vs fortran COMMON
 blocks).

- Do not enable '-z gcs=implicit' on aarch64 for old codestreams.

Update to version 2.45:

 * New versioned release of libsframe.so.2
 * s390: tools now support SFrame format 2, recognize 'z17' as CPU
 name [bsc#1247105, jsc#IBM-1485]
 * sframe sections are now of ELF section type SHT_GNU_SFRAME.
 * sframe secions generated by the assembler have
 SFRAME_F_FDE_FUNC_START_PCREL set.
 * riscv: Support more extensions: standard: Zicfiss v1.0, Zicfilp v1.0,
 Zcmp v1.0, Zcmt v1.0, Smrnmi v1.0, S[sm]dbltrp v1.0, S[sm]ctr v1.0,
 ssqosid v1.0, ssnpm v1.0, smnpm v1.0, smmpm v1.0, sspm v1.0, supm v1.0,
 sha v1.0, zce v1.0, smcdeleg v1.0, ssccfg v1.0, svvptc v1.0, zilsd v1.0,
 zclsd v1.0, smrnmi v1.0,
 vendor: CORE-V, xcvbitmanip v1.0 and xcvsimd v1.0,
 SiFive, xsfvqmaccdod v1.0, xsfvqmaccqoqv1.0 and xsfvfnrclipxfqf v1.0,
 T-Head: xtheadvdot v1.0,
 MIPS: xmipscbop v1.0, xmipscmov v1.0, xmipsexectl v1.0, xmipslsp v1.0.
 * Support RISC-V privileged version 1.13, profiles 20/22/23, and
 .bfloat16 directive.
 * x86: Add support for these ISAs: Intel Diamond Rapids AMX, MOVRS,
 AVX10.2 (including SM4), MSR_IMM, Zhaoxin PadLock PHE2, RNG2, GMI, XMODX.
 Drop support for AVX10.2 256 bit rounding.
 * arm: Add support for most of Armv9.6, enabled by -march=armv9.6-a and
 extensions '+cmpbr', '+f8f16mm', '+f8f32mm', '+fprcvt', '+lsfe', '+lsui',
 '+occmo', '+pops', '+sme2p2', '+ssve-aes', '+sve-aes', '+sve-aes2',
 '+sve-bfscale', '+sve-f16f32mm' and '+sve2p2'.
 * Predefined symbols 'GAS(version)' and, on non-release builds, 'GAS(date)'
 are now being made available.
 * Add .errif and .warnif directives.
 * linker:
 - Add --image-base=<ADDR> option to the ELF linker to behave the same
 as -Ttext-segment for compatibility with LLD.
 - Add support for mixed LTO and non-LTO codes in relocatable output.
 - s390: linker generates .eh_frame and/or .sframe for linker
 generated .plt sections by default (can be disabled
 by --no-ld-generated-unwind-info).
 - riscv: add new PLT formats, and GNU property merge rules for zicfiss
 and zicfilp extensions.
- gold is no longer included

- Contains fixes for these non-CVEs (not security bugs per upstreams
 SECURITY.md):

 * bsc#1236632 aka CVE-2025-0840 aka PR32560
 * bsc#1236977 aka CVE-2025-1149 aka PR32576
 * bsc#1236978 aka CVE-2025-1148 aka PR32576
 * bsc#1236999 aka CVE-2025-1176 aka PR32636
 * bsc#1237000 aka CVE-2025-1153 aka PR32603
 * bsc#1237001 aka CVE-2025-1152 aka PR32576
 * bsc#1237003 aka CVE-2025-1151 aka PR32576
 * bsc#1237005 aka CVE-2025-1150 aka PR32576
 * bsc#1237018 aka CVE-2025-1178 aka PR32638
 * bsc#1237019 aka CVE-2025-1181 aka PR32643
 * bsc#1237020 aka CVE-2025-1180 aka PR32642
 * bsc#1237021 aka CVE-2025-1179 aka PR32640
 * ... [Please see the references for more information on the vulnerabilities]");

  script_tag(name:"affected", value:"'binutils' package(s) on SUSE Linux Enterprise Server 16.0, SUSE Linux Enterprise Server for SAP applications 16.0.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "SLES16.0.0") {

  if(!isnull(res = isrpmvuln(pkg:"binutils", rpm:"binutils~2.45~160000.1.1", rls:"SLES16.0.0"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"binutils-devel", rpm:"binutils-devel~2.45~160000.1.1", rls:"SLES16.0.0"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"bpftool", rpm:"bpftool~7.5.0~160000.2.3", rls:"SLES16.0.0"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"bpftool-bash-completion", rpm:"bpftool-bash-completion~7.5.0~160000.2.3", rls:"SLES16.0.0"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"gprofng", rpm:"gprofng~2.45~160000.1.1", rls:"SLES16.0.0"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libctf-nobfd0", rpm:"libctf-nobfd0~2.45~160000.1.1", rls:"SLES16.0.0"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libctf0", rpm:"libctf0~2.45~160000.1.1", rls:"SLES16.0.0"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
